name: Deploy to AWS Server

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment (optional)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies (if needed)
      - name: Install Dependencies
        run: |
          npm install || echo "No dependencies to install"

      # Step 4: Build the static site
      - name: Build Static Site
        run: |
          echo "Building static site..." 
          # Replace this with your actual build command if you have one, e.g., `npm run build`
          # For now, just an example to simulate a build process
          touch ./index.html ./style.css 
          
      # Step 5: Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh_private_key: ${{ secrets.AWS_SSH_KEY }}

      # Step 6: Add AWS Server to known_hosts
      - name: Add AWS Server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.AWS_SERVER_IP }} >> ~/.ssh/known_hosts

      # Step 7: Deploy to AWS Server
      - name: Deploy to AWS Server
        run: |
          echo "Deploying to AWS server..."
          # Deploy the built site (located in ./dist)
          scp -r ./* ubuntu@${{ secrets.AWS_SERVER_IP }}:/var/www/html/
