name: Deploy to AWS EC2 Server

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup SSH with the provided .pem key
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PEM_FILE }}" > ~/.ssh/aws_ec2_key.pem
          chmod 600 ~/.ssh/aws_ec2_key.pem

      # Step 3: Add AWS server to known_hosts
      - name: Add AWS Server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.AWS_SERVER_IP }} >> ~/.ssh/known_hosts

      # Step 4: Deploy the app via SSH
      - name: Deploy to EC2 Server
        run: |
          echo "Connecting to the server and deploying the app..."
          ssh -i ~/.ssh/aws_ec2_key.pem ubuntu@${{ secrets.AWS_SERVER_IP }} "sudo mkdir -p /var/www/html && sudo chown ubuntu:ubuntu /var/www/html"
          scp -i ~/.ssh/aws_ec2_key.pem -r ./index.html ./style.css ./images ubuntu@${{ secrets.AWS_SERVER_IP }}:/var/www/html/
